AxolotlProject/Models/UserPost.cs
using System.Text.RegularExpressions;

namespace AxolotlProject.Models;

public class UserPost
{
    public Guid Id { get; set; }
    public DateTime CreationTime { get; set; } = DateTime.Now;
    public string? Heading { get; set; }
    public string? Content { get; set; }
    public PostCategory PostCategory { get; set; }
    public string? UserId { get; set; }
    public User? User { get; set; }
    public List<Comment>? Comments { get; set; }
    public List<PostMark>? Marks { get; set; }
    public IEnumerable<string>? Tags
    {
        get
        {
            Regex r = new Regex(@"\#.\w*", RegexOptions.IgnoreCase);
            List<string> matches = new();
            if (Heading is null || Content is null)
                throw new ArgumentNullException();
            return matches
                            .Concat(r.Matches(Heading).Cast<Match>().Select(match => match.Value))
                            .Concat(r.Matches(Content).Cast<Match>().Select(match => match.Value))
                                                        .Distinct();
        }
    }

    public int CountRating()
    {
        int count = 0;
        if (Marks == null)
        {
            return 0;
        }
        foreach (var mark in Marks)
        {
            if (mark.Liked) count++;
            else count--;
        }
        return count;
    }

    public string GetShortContent(int size = 500)
    {
        if (!string.IsNullOrEmpty(Content))
        {
            if (Content.Length > size)
            {
                return string.Concat(Content.AsSpan(0, size), "...");
            }
            return Content;
        }
        return "No content";
    }

    public Comment? GetLastComment()
    {
        if (Comments == null || Comments.Count == 0) return null;
        return Comments[Comments.Count - 1];
    }
}

AxolotlProject/Controllers/UserPostController.cs
using AxolotlProject.Models;
using Microsoft.AspNetCore.Mvc;
using AxolotlProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace AxolotlProject.Controllers
{
    public class UserPostController : Controller
    {
        private readonly ILogger<UserPostController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public UserPostController(ILogger<UserPostController> logger, ApplicationDbContext context, UserManager<User> userManager)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string? search, string? category, int num, bool nameSearch = false, bool authorSearch = false, bool tagsSearch = false, string? addFilt = null)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if(_context.IsUserBanned(user?.Id, PostCategory.All)) 
                return Forbid();

            List<UserPost> result = await _context.UserPosts!.ToListAsync();
            if (category is not null)
                result = result.Where(post => post.PostCategory!.ToString().Equals(category)).ToList();
            if (search is not null)
            {
                result = result.Where(post =>
                    (nameSearch && post.Heading is not null && (post.Heading!.Trim().ToLower().Contains(search.Trim().ToLower()) || search.Trim().ToLower().Contains(post.Heading.Trim().ToLower()))) ||
                    (authorSearch && _context.Users?.Find(post.UserId) is not null && (post.User!.Login!.Trim().ToLower().Contains(search.Trim().ToLower()) || search.Trim().ToLower().Contains(post.User.Login.Trim().ToLower()))) ||
                    (tagsSearch && post.Tags.Any(t => t.Trim().ToLower().Contains(search.Trim().ToLower()) || search.Trim().ToLower().Contains(t.Trim().Remove(0, 1).ToLower()))))
                .ToList();
            }

            ViewBag.ViewerId = user?.Id;
            ViewBag.Search = search;
            ViewBag.Category = category;
            ViewBag.NameSearch = nameSearch;
            ViewBag.AuthorSearch = authorSearch;
            ViewBag.TagsSearch = tagsSearch;
            ViewBag.Num = num;
            ViewBag.AddFilt = addFilt;
            ViewBag.CommentsAmount = result.ToDictionary(p => p.Id, p => _context.Comments?.Where(comment => comment.PostId.Equals(p.Id)).Count());
            ViewBag.Rating = result.ToDictionary(p => p.Id,
                                p => _context.PostsMarks?
                                        .Where(m => m.PostId.Equals(p.Id))
                                        .Select(m => m.Liked ? 1 : -1).AsEnumerable()
                                        .Aggregate(0, (x, y) => x + y));

            if (addFilt is not null)
            {
                if (addFilt.Equals("popular")) result = result.Where(p => ViewBag.Rating[p.Id] >= 5).ToList();
                else if (addFilt.Equals("commented")) result = result.Where(p => ViewBag.CommentsAmount[p.Id] > 0).ToList();
                else if (addFilt.Equals("my")) result = result.Where(p => p.UserId!.Equals(user?.Id)).ToList();
            }

            int postsAmount = 5;
            num = num < 0 ? 0 : num;
            num = num > (result.Count - 1) / postsAmount ? (result.Count - 1) / postsAmount : num;
            int left = num * postsAmount,
                right = (left + postsAmount) is int r && r < result.Count ? r : result.Count;
            Dictionary<Guid, User?> PostOwners = result.ToDictionary(p => p.Id, p => _context.Users.FirstOrDefault(u => p.UserId.Equals(u.Id)));
            return View(result.ToArray<UserPost>()[left..right]);
        }

        [Authorize]
        public async Task<IActionResult> CreatePost()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if(_context.IsUserBanned(user?.Id, PostCategory.All)) 
                return Forbid();
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost([Bind("Id,Heading,Content,PostCategory")] UserPost post)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if(_context.IsUserBanned(user?.Id, PostCategory.All) || _context.IsUserBanned(user?.Id, post.PostCategory)) 
                return Forbid();
            if (ModelState.IsValid)
            {
                post.User = user;
                post.UserId = user.Id;
                //post.CreationTime = DateTime.Now; //UPDATE DB MIGRATIONS
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        [Authorize]
        public async Task<IActionResult> EditPost(Guid? id)
        {
            var post = await _context.UserPosts!.FindAsync(id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (id == null || _context.UserPosts == null || post == null)
                return NotFound();
            if(_context.IsUserBanned(user?.Id, PostCategory.All) || _context.IsUserBanned(user?.Id, post.PostCategory)) 
                return Forbid();
            return user.Id == post.UserId ? View(post) : RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(Guid? id, string Heading, string Content, PostCategory PostCategory)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var post = await _context.UserPosts!.FirstOrDefaultAsync(p => p.Id == id);
            if(_context.IsUserBanned(user?.Id, PostCategory.All) || _context.IsUserBanned(user?.Id, post!.PostCategory)) 
                return Forbid();
            if (id != post?.Id) return NotFound();
            if (user.Id == post?.UserId)
            {
                post.Heading = Heading;
                post.Content = Content;
                post.PostCategory = PostCategory;
                _context.Update(post);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpPost, ActionName("DeletePost")]
        public async Task<IActionResult> DeletePost(Guid postId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var post = await _context.UserPosts!.FirstOrDefaultAsync(p => p.Id == postId);
            if(_context.IsUserBanned(user?.Id, PostCategory.All) || _context.IsUserBanned(user?.Id, post.PostCategory)) 
                return Forbid();
            if (user == null || post == null) return NotFound();
            if (user.Id == post.UserId)
            {
                _context.Remove(post);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ShowPost(Guid? postId)
        {
            if (postId == null || _context.UserPosts == null)
            {
                return NotFound();
            }

            var post = await _context.UserPosts
                .FirstOrDefaultAsync(p => p.Id == postId);
            if (post == null)
            {
                return NotFound();
            }

            ViewBag.PostOwner = _context.Users?.Find(post.UserId);
            ViewBag.OwnerPostsAmount = _context.UserPosts?.Where(p => p.UserId == post.UserId).Count();
            ViewBag.Comments = _context.Comments?.Where(comment => comment.PostId.Equals(postId)).ToList();
            var commentsOwners = new Dictionary<Guid, User?>();
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if(_context.IsUserBanned(user?.Id, PostCategory.All) || _context.IsUserBanned(user?.Id, post.PostCategory)) 
                return Forbid();
            ViewBag.ViewerId = user?.Id;
            foreach (var item in ViewBag.Comments)
            {
                commentsOwners.Add(item.Id, _context.Users?.Find(item.UserId));
            }
            ViewBag.CommentsOwners = commentsOwners;
            ViewBag.CommentsRating = _context.Comments?.Where(c => c.PostId.Equals(postId))
                .ToDictionary(
                        c => c.Id,
                        c => _context.CommentsMarks?
                            .Where(mark => mark.CommentId.Equals(c.Id))
                            .Select(mark => mark.Liked ? 1 : -1).AsEnumerable()
                            .Aggregate(0, (x, y) => x + y)
                        );

            ViewBag.Rating = _context.PostsMarks?
                .Where(m => m.PostId.Equals(postId))
                .Select(m => m.Liked ? 1 : -1).AsEnumerable()
                .Aggregate(0, (x, y) => x + y);

            return View(post);
        }

        [Authorize]
        [HttpPost, ActionName("CreateComment")]
        public async Task<IActionResult> CreateComment(string commentContent, Guid postId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var post = await _context.UserPosts!.FirstOrDefaultAsync(p => p.Id == postId);
            if (user == null || post == null) return NotFound();
            if(_context.IsUserBanned(user?.Id, PostCategory.All) || _context.IsUserBanned(user?.Id, post.PostCategory)) 
                return Forbid();
            var comment = new Comment()
            {
                Id = Guid.NewGuid(),
                Content = commentContent,
                CommentMarks = new List<CommentMark>(),
                User = user,
                UserId = user?.Id,
                Post = post,

AxolotlProject/Views/UserPost/CreatePost.cshtml
@using AxolotlProject.Models
@model UserPost

<link rel="stylesheet" href="~/css/create_post.css" asp-append-version="true" />

<div id="page-container">
    <div class="main-container">
        <div class="main-container__container">
            <div class="header-text">
                <span>Post creating</span>
            </div>

            <div class="form">
                <form method="post" asp-controller="UserPost" asp-action="CreatePost">
                    <div class="select-category">
                        <span>
                            Select category:
                            <select name="PostCategory">
                                @foreach (PostCategory pc in (PostCategory[])Enum.GetValues(typeof(PostCategory)))
                                {
                                    <option value=@pc>@pc</option>
                                }
                            </select>
                        </span>
                    </div>
                    <div class="bbcodes">
                        <input type="button" value="b" class="bbcode" onclick="formatText ('b');" title="Bolder text" />
                        <input type="button" value="i" class="bbcode" onclick="formatText ('i');" title="Italic text" />
                        <input type="button" value="s" class="bbcode" onclick="formatText ('s');" title="Crossed text" />
                        <input type="button" value="u" class="bbcode" onclick="formatText ('u');" title="Underlined text" />
                        <input type="button" value="center" class="bbcode" onclick="formatText ('center');" title="Centered text" />
                        <input type="button" value="right" class="bbcode" onclick="formatText ('right');" title="Right aligned text" />
                        <input type="button" value="justify" class="bbcode" onclick="formatText ('justify');" title="Aligned text" />
                        <input type="button" value="table" class="bbcode" onclick="formatText ('table');" title="Main table tag" />
                        <input type="button" value="tr" class="bbcode" onclick="formatText ('tr');" title="Table tag" />
                        <input type="button" value="td" class="bbcode" onclick="formatText ('td');" title="Table tag" />
                    </div>
                    <div class="heading_place">
                        <label asp-for="Heading"></label>
                        <input asp-for="Heading" id="heading" placeholder="Heaging of the post" required />
                    </div>
                    <div class="textarea_place">
                        <label asp-for="Content"></label>
                        <textarea asp-for="Content" id="post" placeholder="Text of the post"></textarea>
                    </div>
                    <div class="select-tags">
                        <span>Select tags:</span>
                    </div>
                    <div class="agree">
                        <label>
                            <input type="checkbox" required>
                            I have read and agree to 4K-dev_Project's User Agreement and rules
                        </label>
                    </div>
                    <div class="buttons">
                        <input type="submit" class="submit-buttons" value="Create Post">
                        <input type="button" class="submit-buttons" value="Preview"> @*???*@
                    </div>
                    <div class="questions">
                        <span>Still have questions with post's creating process? Read the <a href="#">documentation</a>.</span>
                    </div>
                </form>
                <div class="preview"> @*???*@
                    <div>Preview</div>
                    <div class="preview_field">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AxolotlProject/Views/UserPost/EditComment.cshtml
@using AxolotlProject.Models
@model Comment

<link rel="stylesheet" href="~/css/create_post.css" asp-append-version="true" />

<div id="page-container">
    <div class="main-container">
        <div class="main-container__container">
            <div class="header-text">
                <span>Comment editing</span>
            </div>
            <div class="form">
                <form method="post" asp-controller="UserPost" asp-action="EditComment" asp-route-id="@Model.Id">
                    <div class="textarea_pserPost/EditPostlace">
                        <label asp-for="Content"></label>
                        <textarea asp-for="Content" id="post" placeholder="Text of the post"></textarea>
                    </div>
                    <div class="buttons">
                        <input type="submit" class="submit-buttons" value="Save Changes">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

AxolotlProject/Views/UserPost/EditPost.cshtml
@using AxolotlProject.Models
@model UserPost

<link rel="stylesheet" href="~/css/create_post.css" asp-append-version="true" />

<div id="page-container">
    <div class="main-container">
        <div class="main-container__container">
            <div class="header-text">
                <span>Post editing</span>
            </div>

            <div class="form">
                <form method="post" asp-controller="UserPost" asp-action="EditPost" asp-route-id="@Model.Id">
                    <div class="select-category">
                        <span>
                            Select category:
                            <select name="PostCategory">
                                @foreach (PostCategory pc in (PostCategory[])Enum.GetValues(typeof(PostCategory)))
                                {
                                    <option value=@pc>@pc</option>
                                }
                            </select>
                        </span>
                    </div>
                    <div class="bbcodes">
                        <input type="button" value="b" class="bbcode" onclick="formatText ('b');" title="Bolder text" />
                        <input type="button" value="i" class="bbcode" onclick="formatText ('i');" title="Italic text" />
                        <input type="button" value="s" class="bbcode" onclick="formatText ('s');" title="Crossed text" />
                        <input type="button" value="u" class="bbcode" onclick="formatText ('u');" title="Underlined text" />
                        <input type="button" value="center" class="bbcode" onclick="formatText ('center');" title="Centered text" />
                        <input type="button" value="right" class="bbcode" onclick="formatText ('right');" title="Right aligned text" />
                        <input type="button" value="justify" class="bbcode" onclick="formatText ('justify');" title="Aligned text" />
                        <input type="button" value="table" class="bbcode" onclick="formatText ('table');" title="Main table tag" />
                        <input type="button" value="tr" class="bbcode" onclick="formatText ('tr');" title="Table tag" />
                        <input type="button" value="td" class="bbcode" onclick="formatText ('td');" title="Table tag" />
                    </div>
                    <div class="heading_place">
                        <label asp-for="Heading"></label>
                        <input asp-for="Heading" id="heading" placeholder="Heaging of the post" required />
                    </div>
                    <div class="textarea_pserPost/EditPostlace">
                        <label asp-for="Content"></label>
                        <textarea asp-for="Content" id="post" placeholder="Text of the post"></textarea>
                    </div>
                    <div class="select-tags">
                        <span>Select tags:</span>
                    </div>
                    <div class="buttons">
                        <input type="submit" class="submit-buttons" value="Save Changes">
                        <input type="button" class="submit-buttons" value="Preview"> @*???*@
                    </div>
                    <div class="questions">
                        <span>Still have questions with post's creating process? Read the <a href="#">documentation</a>.</span>
                    </div>
                </form>
                <div class="preview"> @*???*@
                    <div>Preview</div>
                    <div class="preview_field">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AxolotlProject/Views/UserPost/ShowPost.cshtml
@using AxolotlProject.Models
@model UserPost

<link rel="stylesheet" href="~/css/post.css" asp-append-version="true" />

<div id="page-container">
    <div class="main-container">
        <div class="main-container__left">
            <div class="left__container">
                <div class="post-block">
                    <div class="post-block__title">
                        <span class="header-text">@Model.Heading</span>
                    </div>
                    <div class="post">
                        <div class="post-text"><span>
                            @Model.Content
                        </span></div>
                        <div class="post-reactions">
                            <a class="like" asp-action="MarkPost" asp-route-postId="@Model.Id" asp-route-mark="true">
                                <i class="fa-solid fa-thumbs-up reaction"></i>
                            </a>
                            <div class="number">
															@(ViewBag.Rating??0)
                            </div>
                            <a class="dislike" asp-action="MarkPost" asp-route-postId="@Model.Id" asp-route-mark="false">
                                <i class="fa-solid fa-thumbs-down reaction"></i>
                            </a>
                                @*
                                    ADD EDITING AND DELETING FITURE
                                    IF IT`S USER`S POST
                                *@
                        </div>
                    </div>
                    <div class="post-info">
                        <div><span>Category: @Model.PostCategory</span></div>
                        <div>
                            <span>
                                @* Tags: @Model.GetTagsAsString() *@
                            </span>
                        </div>
                    </div>
                </div>
                <div class="comment-block">
                    <div class="comment-block__title">
                        <span class="header-text">Comments</span>
                    </div>
                    <form method="post" asp-controller="UserPost" asp-action="CreateComment" 
                        asp-route-postId=@Model.Id class="commentForm">
                        <p>
                            <label for="commentContent">Create comment:</label>
                        </p>
                        <textarea name="commentContent" rows="4" cols="50" required>Some text</textarea>
                        <p>
                            <input type="submit" value="Add Comment"/>
                        </p>
                    </form>

                    <div class="comments">
                        <div class="comments-text">
                            @foreach (var comment in ViewBag.Comments){
                                <div class="commentBlock">
                                    <div class="comment-content">
                                        <h3><a  class="page_link" asp-area="Identity" asp-page="/Account/Manage/Profile" asp-route-id="@ViewBag.CommentsOwners[comment.Id].Id" title="Profile">
                                    @ViewBag.CommentsOwners[comment.Id].Login
                                </a></h3>
																				@comment.CreationTime<br/>
                                        @comment.Content
                                    </div>
                                    <div class="comment-reactions">
                                        <div class="like">
                                            <a asp-action="MarkComment" asp-route-commentId="@comment.Id" asp-route-mark="true">
																							&#9650
																						</a>
                                        </div>
                                        <div class="number">
                                            @ViewBag.CommentsRating[comment.Id]
                                        </div>
                                        <div class="dislike">
                                            <a asp-action="MarkComment" asp-route-commentId="@comment.Id" asp-route-mark="false">&#9660</a> @*or &#9661*@
                                        </div>
                                    </div>
                                </div>
                                <div class="commentManagement">
                                    @if(User.Identity.IsAuthenticated && comment.UserId == ViewBag.ViewerId){
                                        <a asp-action="EditComment" asp-route-id="@comment.Id" style="display:inline-block"><button>Edit</button></a>
                                            <form style="display:inline-block" method="post" asp-controller="UserPost" asp-action="DeleteComment"
                                          asp-route-postId=@Model.Id asp-route-commentId=@comment.Id style="display:inline-block">
                                            <input type="submit" value="Delete Comment"/>
                                        </form>
                                    }
                                </div>
                                <hr />
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="main-container__right">
            <div class="right__container-information">
                <div class="information__title">
                    <span class="header-text">Author</span>
                </div>
                <hr>
                <h2><a  class="page_link" asp-area="Identity" asp-page="/Account/Manage/Profile" asp-route-id="@ViewBag.PostOwner?.Id" title="Profile">@ViewBag.PostOwner?.Login</a></h2>
                Has @ViewBag.OwnerPostsAmount post(s)
            </div>
            <div class="right__container-category">
                <div class="category__title">
                    <span class="header-text category">Related to this category</span>
                </div>
                <hr>
                @*Some posts, added to the view model, close by tags etc
                    -> SPRINT #4
                *@
            </div>
        </div>
    </div>
</div>